from spire.scraper.classes.raw_course import RawCourse
from spire.scraper.classes.raw_course_detail import RawCourseDetail
from spire.scraper.classes.raw_course_enrollment_information import RawCourseEnrollmentInformation
from spire.scraper.classes.raw_subject import RawSubject
