version: "3"

volumes:
    static:

services:
    # Web application
    web:
        build: .
        depends_on:
            - cache
        command: python -m gunicorn -c python:config.gunicorn config.wsgi
        environment:
            REDIS_URL: redis://cache:6379
        env_file:
            - .env
        healthcheck:
            test: curl localhost:8000/up
            interval: 60s
            timeout: 3s
            start_period: 5s
            retries: 3
        ports:
            - 8000:8000
        volumes:
            - static:/home/app/static
    # Caching backend used by the web app
    cache:
        image: redis:latest
        ports:
            - 6379:6379
    # Web crawler
    scraper:
        build: .
        depends_on:
            - selenium
        command: python manage.py scrape sections
        environment:
            SELENIUM_SERVER_URL: http://selenium:4444
        env_file:
            - .env
    # Selenium server used by scraper
    selenium:
        image: selenium/standalone-firefox:latest
        ports:
            - 4444:4444
