
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - web

  web:
    restart: unless-stopped
    build: .
    container_name: web
    depends_on:
      - redis
    ports:
      - 8000:8000
    links:
      - redis
    env_file:
      - .env

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

