services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - cache
    working_dir: /app/src
    command: "/bin/sh -c 'python manage.py collectstatic --no-input && python -m gunicorn -c python:config.gunicorn config.wsgi'"
    environment:
      REDIS_URL: redis://cache:6379
    volumes:
      - ./static:/app/static
    ports:
      - 8000:8000
  cache:
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379
