# Generated by Django 4.1.1 on 2022-09-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingroom",
            name="building",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="spire.building",
            ),
        ),
    ]
