# Generated by Django 4.0.5 on 2022-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionrestriction',
            name='add_consent',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sectionrestriction',
            name='drop_consent',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sectionrestriction',
            name='enrollment_requirements',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
