# Generated by Django 4.2.6 on 2023-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0002_alter_sectionmeetinginformation_instructors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicgroup",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["-ordinal"]},
        ),
        migrations.AlterField(
            model_name="section",
            name="overview",
            field=models.CharField(max_length=65536, null=True),
        ),
    ]
