# Generated by Django 4.2.6 on 2023-10-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0003_alter_academicgroup_options_alter_building_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewSectionCombinedAvailability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
                ("wait_list_capacity", models.IntegerField()),
                (
                    "nso_enrollment_capacity",
                    models.IntegerField(default=None, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="sectionavailability",
            name="new_combined_availability",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_availabilities",
                to="spire.newsectioncombinedavailability",
            ),
        ),
    ]
