# Generated by Django 4.0.5 on 2022-07-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0003_alter_sectionrestriction_add_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionrestriction',
            name='add_consent',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='sectionrestriction',
            name='drop_consent',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='sectionrestriction',
            name='enrollment_requirements',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
