# Generated by Django 4.0.5 on 2022-07-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0005_alter_sectiondetail_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionavailability',
            name='nso_enrollment_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
