# Generated by Django 4.2.6 on 2023-10-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spire",
            "0006_rename_newsectioncombinedavailability_sectioncombinedcapacity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectioncoverage",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="sectioncoverage",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="sectionavailability",
            name="combined_capacity",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_availabilities",
                to="spire.sectioncombinedcapacity",
            ),
        ),
        migrations.CreateModel(
            name="SubjectSectionCoverage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("complete", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="spire.subject",
                    ),
                ),
                (
                    "term_coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="spire.sectioncoverage",
                    ),
                ),
            ],
            options={
                "ordering": ["term_coverage", "subject"],
                "unique_together": {("term_coverage", "subject")},
            },
        ),
    ]
