# Generated by Django 4.2.6 on 2023-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0007_remove_sectioncoverage_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectioncoverage",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
