# Generated by Django 4.2.6 on 2023-10-27 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0008_sectioncoverage_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectsectioncoverage",
            old_name="complete",
            new_name="completed",
        ),
    ]
