# Generated by Django 4.2.6 on 2023-10-27 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0009_rename_complete_subjectsectioncoverage_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectioncoverage",
            name="term",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="coverage",
                serialize=False,
                to="spire.term",
            ),
        ),
    ]
