# Generated by Django 4.0.6 on 2022-07-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0009_course_offerings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offerings',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='spire.course'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='spire.subject'),
        ),
    ]
