# Generated by Django 4.2.6 on 2023-10-31 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0010_alter_sectioncoverage_term"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("offering", "spire_id")},
        ),
    ]
