# Generated by Django 4.0.6 on 2022-07-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0010_remove_course_offerings_remove_course_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginformation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_information', to='spire.sectionv2'),
        ),
        migrations.AlterField(
            model_name='sectionavailability',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='availability', serialize=False, to='spire.sectionv2'),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='spire.sectionv2'),
        ),
        migrations.AlterField(
            model_name='sectionrestriction',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restrictions', serialize=False, to='spire.sectionv2'),
        ),
    ]
