# Generated by Django 4.0.6 on 2022-07-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0011_alter_meetinginformation_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
