# Generated by Django 4.2.6 on 2023-10-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spire", "0011_alter_section_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="ordinal",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="termevent",
            unique_together={("term", "description", "date")},
        ),
    ]
