# Generated by Django 4.0.6 on 2022-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0013_rename_sectionv2_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(related_name='subjects', to='spire.academicgroup'),
        ),
    ]
