# Generated by Django 4.0.6 on 2022-07-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0015_rename_combinedsectionavailability_sectioncombinedavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'ordering': ['id']},
        ),
    ]
