# Generated by Django 4.1 on 2022-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spire", "0016_alter_academicgroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectionavailability",
            options={"ordering": ["section"]},
        ),
        migrations.AlterModelOptions(
            name="sectioncombinedavailability",
            options={"ordering": ["individual_availability"]},
        ),
        migrations.AlterModelOptions(
            name="sectionrestriction",
            options={"ordering": ["section"]},
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="grading_basis",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
