# Generated by Django 4.0.5 on 2022-06-08 15:43

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("spire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="_updated_at",
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name="section",
            name="_updated_at",
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 0, 0, tzinfo=utc)),
        ),
    ]
