# Generated by Django 4.0.5 on 2022-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_information',
            field=models.JSONField(null=True),
        ),
    ]
