# Generated by Django 4.0.5 on 2022-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiondetail',
            old_name='rap_tap_hcl',
            new_name='rap_tap_hlc',
        ),
        migrations.AddField(
            model_name='sectiondetail',
            name='session',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
