# Generated by Django 4.0.5 on 2022-06-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetinginformation',
            unique_together={('section', 'room', 'days_and_times')},
        ),
    ]
