# Generated by Django 4.0.5 on 2022-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0002_rename_rap_tap_hcl_sectiondetail_rap_tap_hlc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='career',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='gened',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='grading',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='rap_tap_hlc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='session',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='units',
            field=models.CharField(max_length=64),
        ),
    ]
