# Generated by Django 4.0.5 on 2022-06-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0002_alter_combinedsectionavailability_individual_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionRestrictions',
            new_name='SectionRestriction',
        ),
    ]
