# Generated by Django 4.0.5 on 2022-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0002_alter_meetinginformation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
