# Generated by Django 4.0.5 on 2022-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0002_course_details_course_enrollment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
