# Generated by Django 4.0.5 on 2022-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0003_alter_sectiondetail_career_alter_sectiondetail_gened_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectiondetail',
            options={'ordering': ['section']},
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='overview',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
