# Generated by Django 4.0.5 on 2022-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0003_alter_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='overview',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='class_number',
            field=models.IntegerField(unique=True),
        ),
    ]
