# Generated by Django 4.0.5 on 2022-06-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0003_alter_course_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
