# Generated by Django 4.0.5 on 2022-06-11 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='must be a course ID (match course ID RegExp)', regex='^(?P<subject_id>[A-Z\\-]{2,9}[A-Z]) (?P<course_number>[A-Za-z0-9\\-]{1,9}[A-Za-z0-9])$')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='must be a course ID number (match course title number RegExp)', regex='^(?P<course_number>[A-Za-z0-9\\-]{1,9}[A-Za-z0-9])$')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='must be a  title (match subject id RegExp)', regex='^(?P<subject_id>[A-Z\\-]{2,9}[A-Z])$')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='must be a  title (match subject title RegExp)', regex='^(?P<subject_title>[A-Za-z\\- :&]{2,99}[a-z])$')]),
        ),
    ]
