# Generated by Django 4.0.5 on 2022-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0004_alter_sectiondetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondetail',
            name='topic',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
