# Generated by Django 4.0.5 on 2022-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0004_alter_sectionrestriction_add_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='class_number',
            field=models.IntegerField(),
        ),
    ]
