# Generated by Django 4.0.5 on 2022-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0004_alter_section_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='overview',
            field=models.CharField(max_length=32768, null=True),
        ),
    ]
