# Generated by Django 4.0.5 on 2022-06-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0005_alter_section_overview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetinginformation',
            unique_together={('section', 'room', 'days_and_times', 'meeting_dates')},
        ),
    ]
