# Generated by Django 4.0.5 on 2022-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0005_sectiondetail_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='gened',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='rap_tap_hlc',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
