# Generated by Django 4.0.5 on 2022-06-19 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0006_alter_sectiondetail_gened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='must be a course ID (match course ID RegExp)', regex='^(?P<subject_id>[A-Z\\-@]{2,9}[A-Z]) (?P<course_number>[\\x00-\\x7F]{1,9}[A-Za-z0-9])$')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='must be a course ID (match course ID RegExp)', regex='^(?P<subject_id>[A-Z\\-@]{2,9}[A-Z]) (?P<course_number>[\\x00-\\x7F]{1,9}[A-Za-z0-9])$')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='must be a section id (match the id RegExp', regex='^(?P<section_id>(\\d{2,4})?([A-Z]{1,4})?-[A-Z]{1,4}\\(\\d{3,10}\\))$')]),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='career',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='class_components',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='grading',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondetail',
            name='units',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='must be a  title (match subject id RegExp)', regex='^(?P<subject_id>[A-Z\\-@]{2,9}[A-Z])$')]),
        ),
    ]
