# Generated by Django 4.0.5 on 2022-06-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0006_alter_meetinginformation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetinginformation',
            unique_together=set(),
        ),
    ]
