# Generated by Django 4.0.5 on 2022-06-20 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0007_alter_course_id_alter_section_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='must be a section id (match the id RegExp', regex='^(?P<section_id>([A-Z0-9]{1,6})-[A-Z]{1,4}\\(\\d{3,10}\\))$')]),
        ),
    ]
