# Generated by Django 4.0.6 on 2022-07-23 02:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0007_combinedsectionavailability_nso_enrollment_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternative_title', models.CharField(max_length=256, null=True)),
                ('term', models.CharField(max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spire.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spire.subject')),
            ],
            options={
                'ordering': ['term', 'course'],
                'unique_together': {('course', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SectionV2',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='must be a section id (match the id RegExp', regex='^(?P<section_id>([A-Z0-9]{1,6})-[A-Z]{1,4}\\(\\d{3,10}\\))$')])),
                ('description', models.CharField(max_length=4096, null=True)),
                ('overview', models.CharField(max_length=32768, null=True)),
                ('_updated_at', models.DateTimeField()),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='spire.courseoffering')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
