# Generated by Django 4.0.5 on 2022-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0007_alter_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
