# Generated by Django 4.0.5 on 2022-06-13 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0008_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='must be a  title (match subject title RegExp)', regex='^(?P<subject_title>[A-Za-z\\- :&\\(\\)]{2,99}[a-z])$')]),
        ),
    ]
