# Generated by Django 4.0.5 on 2022-06-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0008_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='gened',
            field=models.JSONField(null=True),
        ),
    ]
