# Generated by Django 4.0.6 on 2022-07-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire', '0014_academicgroup_subject_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombinedSectionAvailability',
            new_name='SectionCombinedAvailability',
        ),
    ]
